export const employeeList =[{
    id: 0,
    name: 'Mihai',
    age: 45,
    gender: 'Male',
    position: 'BE',
    company: 'Glob',
  },
{
    id: 1,
    name: 'Dana',
    age: 21,
    gender: 'Female',
    position: 'FE',
    company: 'Code Impact',
  },
  {
    id: 0,
    name: 'Mihai',
    age: 45,
    gender: 'Male',
    position: 'BE',
    company: 'Globant',
  },
{
    id: 1,
    name: 'Ana',
    age: 21,
    gender: 'Female',
    position: 'FE',
    company: 'Code Impact',
  },{
    id: 0,
    name: 'Marius',
    age: 45,
    gender: 'Male',
    position: 'FE',
    company: 'Glob',
  },
{
    id: 1,
    name: 'Ioana',
    age: 21,
    gender: 'Female',
    position: 'BE',
    company: 'Code Impact',
  }]; 